### ISSUE TITLE
ERROR after upgrade new docker image

### ISSUE THREAD

**Issue by taozhiyuai** [OpenGenerativeAI/llm-colosseum#52]
ERROR after upgrade new docker image

@oulianov 

`(streetfighter) taozhiyu@603e5f4a42f1 llm-colosseum % make local

diambra -r ~/.diambra/roms run -l python3 ollama.py

🖥️  Starting DIAMBRA environment:

🖥️  logged in

v2.2: Pulling from diambra/engine

cf584053a88a: Pull complete 

Digest: sha256:77ba99e5d7d099fe2db292fc7b4e43da310e1bbdb0bcc3a157810e1f933ec81d

Status: Downloaded newer image for diambra/engine:v2.2

Stored credentials found.

Authorization granted.

Server listening on 0.0.0.0:50051

🖥️  DIAMBRA environment started

Traceback (most recent call last):

  File "/Users/taozhiyu/Downloads/llm-colosseum/ollama.py", line 4, in <module>

    from eval.game import Game, Player1, Player2

  File "/Users/taozhiyu/Downloads/llm-colosseum/eval/game.py", line 8, in <module>

    from agent import KEN_GREEN, KEN_RED, Robot

  File "/Users/taozhiyu/Downloads/llm-colosseum/agent/__init__.py", line 6, in <module>

    from .robot import Robot

  File "/Users/taozhiyu/Downloads/llm-colosseum/agent/robot.py", line 11, in <module>

    from llama_index.core.llms import ChatMessage

ModuleNotFoundError: No module named 'llama_index'

🖥️  Couldn't run: exit status 1

make: *** [local] Error 1

`

**Comment by taozhiyuai** [comment]
pip3 install llama_index

done!
