### ISSUE TITLE
🏟️ (9ef4) Error: Wrong rom file for sfiii3n:

### ISSUE THREAD

**Issue by sevaroy** [OpenGenerativeAI/llm-colosseum#56]
(0)Environment initialization ...
🏟️ (9ef4) Error: Wrong rom file for sfiii3n:
 - Correct SHA256 = 7239b5eb005488db22ace477501c574e9420c0ab70aeeb0795dfeb474284d416
 - Found   SHA256 = 7396a705285ad537be03886b3d1ebbf3e2bd6c9a2506aa4b6512be503b1edb8f
------------------------------------------------------------------------------------------------------

        Contact support on DIAMBRA Discord Server: https://diambra.ai/discord
                                        AND / OR
 Open a ticket on our GitHub repository issue Tracker: https://github.com/diambra/arena/issues

------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\kehua\Desktop\llm-colosseum-main\arena\Lib\site-packages\diambra\arena\engine\interface.py", line 31, in env_init
    response = self.client.EnvInit(env_settings_pb)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kehua\Desktop\llm-colosseum-main\arena\Lib\site-packages\grpc\_channel.py", line 1176, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kehua\Desktop\llm-colosseum-main\arena\Lib\site-packages\grpc\_channel.py", line 1005, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.CANCELLED
        details = "Wrong rom file for sfiii3n:
 - Correct SHA256 = 7239b5eb005488db22ace477501c574e9420c0ab70aeeb0795dfeb474284d416
 - Found   SHA256 = 7396a705285ad537be03886b3d1ebbf3e2bd6c9a2506aa4b6512be503b1edb8f"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-07-26T17:15:18.1333875+00:00", grpc_status:1, grpc_message:"Wrong rom file for sfiii3n:\n - Correct SHA256 = 7239b5eb005488db22ace477501c574e9420c0ab70aeeb0795dfeb474284d416\n - Found   SHA256 = 7396a705285ad537be03886b3d1ebbf3e2bd6c9a2506aa4b6512be503b1edb8f"}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kehua\Desktop\llm-colosseum-main\script.py", line 30, in <module>
    main()
  File "C:\Users\kehua\Desktop\llm-colosseum-main\script.py", line 15, in main
    game = Game(
           ^^^^^
  File "C:\Users\kehua\Desktop\llm-colosseum-main\eval\game.py", line 174, in __init__
    self.env = self._init_env(self.settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kehua\Desktop\llm-colosseum-main\eval\game.py", line 239, in _init_env
    return make("sfiii3n", settings, render_mode=render_mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kehua\Desktop\llm-colosseum-main\arena\Lib\site-packages\diambra\arena\make_env.py", line 45, in make
    env = DiambraGym2P(env_settings)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kehua\Desktop\llm-colosseum-main\arena\Lib\site-packages\diambra\arena\arena_gym.py", line 256, in __init__
    super().__init__(env_settings)
  File "C:\Users\kehua\Desktop\llm-colosseum-main\arena\Lib\site-packages\diambra\arena\arena_gym.py", line 38, in __init__
    self.env_info = self.arena_engine.env_init(self.env_settings.get_pb_request(init=True))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kehua\Desktop\llm-colosseum-main\arena\Lib\site-packages\diambra\arena\engine\interface.py", line 33, in env_init
    raise Exception(CONNECTION_FAILED_ERROR_TEXT)
Exception: DIAMBRA Arena failed to connect to the Engine Server. Are you running it with DIAMBRA CLI: `diambra run python script.py`?

See the docs (https://docs.diambra.ai) for additional details, or join DIAMBRA Discord Server (https://diambra.ai/discord) for support.
🖥️  Couldn't run: exit status 1

I got this issue IN WIN 11

**Comment by oulianov** [comment]
Hello, make sure you follow all the hints on the [game page](https://docs.diambra.ai/envs/games/sfiii3n/)

Please look at the last two **search keywords** on the game page 

Otherwise, you may find a copy of the American version and not the Japanese version of the game
